#!/usr/bin/env python3
"""
Generate a random CH4 + O2 gas mixture data file for LAMMPS.

Outputs a LAMMPS data file (atom_style charge) with:
- N_CH4 methane molecules
- N_O2 oxygen molecules
- Random positions with overlap avoidance
- Random molecular orientations

Atom types:
  1 = C (12.011 g/mol)
  2 = H (1.008 g/mol)
  3 = O (15.999 g/mol)
"""

import argparse
import math
import random
from typing import List, Tuple

import numpy as np


CH4_COORDS = np.array([
    [0.0000, 0.0000, 0.0000],
    [0.6291, 0.6291, 0.6291],
    [-0.6291, -0.6291, 0.6291],
    [-0.6291, 0.6291, -0.6291],
    [0.6291, -0.6291, -0.6291],
])
CH4_TYPES = [1, 2, 2, 2, 2]
CH4_RADIUS = 1.5

O2_COORDS = np.array([
    [-0.605, 0.0, 0.0],
    [0.605, 0.0, 0.0],
])
O2_TYPES = [3, 3]
O2_RADIUS = 1.0


def random_rotation_matrix() -> np.ndarray:
    """Generate a random 3D rotation matrix using Euler angles."""
    alpha = random.uniform(0, 2 * math.pi)
    beta = random.uniform(0, math.pi)
    gamma = random.uniform(0, 2 * math.pi)

    ca, sa = math.cos(alpha), math.sin(alpha)
    cb, sb = math.cos(beta), math.sin(beta)
    cg, sg = math.cos(gamma), math.sin(gamma)

    R = np.array([
        [ca * cb * cg - sa * sg, -ca * cb * sg - sa * cg, ca * sb],
        [sa * cb * cg + ca * sg, -sa * cb * sg + ca * cg, sa * sb],
        [-sb * cg, sb * sg, cb],
    ])
    return R


def place_molecule(
    coords: np.ndarray,
    center: np.ndarray,
) -> np.ndarray:
    """Place a molecule at the given center with a random rotation."""
    R = random_rotation_matrix()
    rotated = coords @ R.T
    return rotated + center


def check_overlap(
    new_center: np.ndarray,
    new_radius: float,
    existing_centers: List[np.ndarray],
    existing_radii: List[float],
    min_gap: float = 0.5,
) -> bool:
    """Return True if the new molecule overlaps with any existing molecule."""
    for c, r in zip(existing_centers, existing_radii):
        dist = np.linalg.norm(new_center - c)
        if dist < new_radius + r + min_gap:
            return True
    return False


def generate_gasmix(
    n_ch4: int,
    n_o2: int,
    box_size: float,
    seed: int = 42,
    max_attempts: int = 10000,
) -> Tuple[List[np.ndarray], List[int], float]:
    """
    Generate positions and types for a CH4 + O2 gas mixture.
    
    Returns:
        all_positions: list of (N_atoms, 3) arrays for each molecule
        all_types: list of atom type lists for each molecule
        box_size: the actual box size used
    """
    random.seed(seed)
    np.random.seed(seed)

    padding = 2.0
    lo = padding
    hi = box_size - padding

    centers: List[np.ndarray] = []
    radii: List[float] = []
    all_positions: List[np.ndarray] = []
    all_types: List[List[int]] = []

    for _ in range(n_ch4):
        placed = False
        for _ in range(max_attempts):
            center = np.array([
                random.uniform(lo, hi),
                random.uniform(lo, hi),
                random.uniform(lo, hi),
            ])
            if not check_overlap(center, CH4_RADIUS, centers, radii):
                placed = True
                break

        if not placed:
            raise RuntimeError(f"Could not place CH4 molecule after {max_attempts} attempts. Try a larger box.")

        centers.append(center)
        radii.append(CH4_RADIUS)
        all_positions.append(place_molecule(CH4_COORDS, center))
        all_types.append(CH4_TYPES)

    for _ in range(n_o2):
        placed = False
        for _ in range(max_attempts):
            center = np.array([
                random.uniform(lo, hi),
                random.uniform(lo, hi),
                random.uniform(lo, hi),
            ])
            if not check_overlap(center, O2_RADIUS, centers, radii):
                placed = True
                break

        if not placed:
            raise RuntimeError(f"Could not place O2 molecule after {max_attempts} attempts. Try a larger box.")

        centers.append(center)
        radii.append(O2_RADIUS)
        all_positions.append(place_molecule(O2_COORDS, center))
        all_types.append(O2_TYPES)

    return all_positions, all_types, box_size


def write_lammps_data(
    filename: str,
    all_positions: List[np.ndarray],
    all_types: List[List[int]],
    box_size: float,
):
    """Write a LAMMPS data file (atom_style charge)."""
    total_atoms = sum(len(pos) for pos in all_positions)

    with open(filename, "w") as f:
        f.write("# CH4 + O2 gas mixture for ReaxFF\n")
        f.write(f"# Generated by gen_data_gasmix.py\n\n")
        f.write(f"{total_atoms} atoms\n")
        f.write("3 atom types\n\n")
        f.write(f"0.0 {box_size:.6f} xlo xhi\n")
        f.write(f"0.0 {box_size:.6f} ylo yhi\n")
        f.write(f"0.0 {box_size:.6f} zlo zhi\n\n")
        f.write("Masses\n\n")
        f.write("1 12.011  # C\n")
        f.write("2 1.008   # H\n")
        f.write("3 15.999  # O\n\n")
        f.write("Atoms # charge\n\n")

        atom_id = 1
        for positions, types in zip(all_positions, all_types):
            for i, (pos, atype) in enumerate(zip(positions, types)):
                q = 0.0
                f.write(f"{atom_id} {atype} {q:.6f} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n")
                atom_id += 1

    print(f"Wrote {filename} with {total_atoms} atoms")


PRESETS = {
    "small": {"n_ch4": 10, "n_o2": 20, "box": 40.0},      # 90 atoms
    "medium": {"n_ch4": 55, "n_o2": 110, "box": 70.0},    # 495 atoms (~500)
    "large": {"n_ch4": 110, "n_o2": 220, "box": 90.0},    # 990 atoms (~1000)
}


def main():
    parser = argparse.ArgumentParser(
        description="Generate CH4 + O2 gas mixture data file for LAMMPS",
        epilog="Preset sizes: small (~90 atoms), medium (~500 atoms), large (~1000 atoms)",
    )
    parser.add_argument("--preset", type=str, choices=list(PRESETS.keys()), help="Use a preset size")
    parser.add_argument("--n-ch4", type=int, default=None, help="Number of CH4 molecules")
    parser.add_argument("--n-o2", type=int, default=None, help="Number of O2 molecules")
    parser.add_argument("--box", type=float, default=None, help="Box size in Angstroms")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("-o", "--output", type=str, default="data.gasmix_cho.lmp", help="Output filename")
    args = parser.parse_args()

    # Apply preset if specified
    if args.preset:
        preset = PRESETS[args.preset]
        n_ch4 = args.n_ch4 if args.n_ch4 is not None else preset["n_ch4"]
        n_o2 = args.n_o2 if args.n_o2 is not None else preset["n_o2"]
        box = args.box if args.box is not None else preset["box"]
    else:
        n_ch4 = args.n_ch4 if args.n_ch4 is not None else 55
        n_o2 = args.n_o2 if args.n_o2 is not None else 110
        box = args.box if args.box is not None else 70.0

    total_atoms = n_ch4 * 5 + n_o2 * 2
    print(f"Generating mixture: {n_ch4} CH4 + {n_o2} O2 = {total_atoms} atoms")
    print(f"Box size: {box} Å")

    all_positions, all_types, box_size = generate_gasmix(
        n_ch4=n_ch4,
        n_o2=n_o2,
        box_size=box,
        seed=args.seed,
    )

    write_lammps_data(args.output, all_positions, all_types, box_size)

    n_c = n_ch4
    n_h = n_ch4 * 4
    n_o = n_o2 * 2
    print(f"Composition: {n_c} C, {n_h} H, {n_o} O atoms")
    print(f"Box: {box_size} x {box_size} x {box_size} Angstroms")


if __name__ == "__main__":
    main()
